[package]
name = "thematic"
description = "Convert themes between VSCode and Zed formats"
version = "0.1.0"
edition = "2024"
authors = ["C J Silverio <ceejceej@gmail.com>"]
license = "Parity-7.0.0"
readme = "README.md"
repository = "https://github.com/ceejbot/thematic"
homepage = "https://github.com/ceejbot/thematic"

[lib]
name = "thematic"
path = "src/lib.rs"

[[bin]]
name = "thematic"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.0", features = ["derive", "wrap_help"] }
glob = "0.3.2"
home = "0.5.11"
log = "0.4.27"
lovely_env_logger = "0.6.2"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_with = "3.8.1"
slug = "0.1.6"
thiserror = "2.0.12"
toml = "0.8.23"
